name: Feature request
description: Suggest an idea for this project
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem would this feature solve?
      placeholder: Im trying to ...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Be specific about behavior and UX/CLI
      placeholder: Add a flag ... Output should ...
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: I also tried ...
  - type: textarea
    id: context
    attributes:
      label: Additional context
      placeholder: Screenshots, references, similar tools
